name: "Build for Windows"

on: [
  workflow_call,
  pull_request
]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build"
        run: |
          echo "Hello World"