name: "Build for Windows"

on: pull_request

jobs:
  run:
    name: "Build for Windows"
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Test"
        run: |
          echo "Hello, World!"