name: "Build Windows"

runs:
  using: "docker"
  image: "Dockerfile"


inputs:
  arch:
    description: 'Architecture'
    required: true
    default: 'x64'
  node-version:
    description: 'Node.js version'
    required: true
    default: '20.x'