name: 'Build for Windows'
on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                architecture: [x64]
                node-version: [20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                echo "Install for Windows ..."
                sudo apt update
                sudo apt upgrade -y
                sudo apt install build-essential -y
                sudo apt install mingw-w64 -y
                sudo apt install mingw-w64-tools -y
                sudo apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 -y
                if [ "${{ matrix.architecture }}" = "x64" ]; then
                    export CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++"
                fi

            - name: Cache
              uses: actions/cache@v4
              id: npm-cache
              with:
                    path: |
                        ~/.npm
                        node_modules/.cache
                    key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
                    restore-keys: |
                        ${{ matrix.os }}-node-${{ matrix.node-version }}-

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
                cache-dependency-path: package.json

            - name: Install Node.js modules ...
              run: npm install
            
            - name: Environment information
              run: npx envinfo

            - name: Setup C/C++ Compiler
              uses: rlalik/setup-cpp-compiler@v1.2

            - name: Build
              run:  node index.js -p windows -a x64
            