name: 'Build for macOS'
on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Test
              run: |
                npm i
                node index.js -p darwin -a aarch64

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                path: ./ghostpdl-10.03.1/bin/gs.a
                name: gs.a