name: 'Build for macOS'
on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Test
              run: |
                echo "Test for macOS ..."
                clang --target=aarch64-darwin-gnu init.c -o init
                ./init