name: 'Build for macOS'
on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Test
              run: |
                echo "Test for macOS ..."
                curl https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10031/ghostpdl-10.03.1.tar.gz -O -L
                tar -xvf ghostpdl-10.03.1.tar.gz
                cd ghostpdl-10.03.1
                CFLAGS+=--target=aarch64-darwin-gnu ./configure
                make libgs

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                path: ./ghostpdl-10.03.1/bin/gs.a
                name: gs.a