name: 'Build for macOS'
on: [workflow_call]

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:

          matrix:
              os: [macos-latest,macos-13]
              node-version: [20.x]
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Cache
            uses: actions/cache@v4
            id: npm-cache
            with:
              path: |
                  ~/.npm
                  node_modules/.cache
              key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
              restore-keys: |
                  ${{ matrix.os }}-node-${{ matrix.node-version }}-
          
          - name: Install Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
              cache-dependency-path: package.json
              
          - name: Install Node.js modules ...
            run: npm install

          - name: Environment information
            run: npx envinfo
          
          - name: Build
            run: | 
              node index.js 

          - name: Upload build Artifact
            uses: actions/upload-artifact@v4
            with:
              name: ${{ matrix.os == 'macos-latest' && 'gs-darwin-aarch64.tar.gz' || 'gs-darwin-x64.tar.gz' }}
              path: ./${{ matrix.os == 'macos-latest' && 'gs-darwin-aarch64.tar.gz' || 'gs-darwin-x64.tar.gz' }}