name: "Release"
on: 
  release:
    types: [published]
  push:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with: 
          name: |
            gs-windows-x64.tar.gz
            gs-windows-x86.tar.gz

            gs-macos-x64.tar.gz
            gs-macos-aarch64.tar.gz

            gs-linux-x64.tar.gz
            gs-linux-arm64.tar.gz
            gs-linux-armv7.tar.gz
            gs-linux-armv6.tar.gz
      
      - name: Release
        uses: softprops/action-gh-release@v2.0.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt