name: "Release"
on: [push]

jobs:
  release:
    name: "Release"
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build for Windows"
        uses: ./.github/actions/build
        with:
          arch: x64
          os: windows-latest
          node-version: 20.x

      # - name: "Create release"
      #   uses: softprops/action-gh-release@v1

      # - name : "add release"
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       "gs-*-*.tar.gz"