name: "Release"
on: 
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
     

   
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./builds/  

      - name: Build
        run: ls -la    

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            builds/*