name: "Release"
on: 
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7

      - name: Debug
        run: |
          ls -la  
          pwd

      - name: Release
        uses: softprops/action-gh-release@v2.0.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /home/runner/work/libgs/libgs/gs-windows-x86.tar.gz
            /home/runner/work/libgs/libgs/gs-windows-x64.tar.gz
            /home/runner/work/libgs/libgs/gs-darwin-aarch64.tar.gz
            /home/runner/work/libgs/libgs/gs-darwin-x64.tar.gz
            /home/runner/work/libgs/libgs/gs-linux-x64.tar.gz
            /home/runner/work/libgs/libgs/gs-linux-armv7.tar.gz
            /home/runner/work/libgs/libgs/gs-linux-armv6.tar.gz