name: "Release"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: nickNaso/libgs/.github/workflows/builds/windows.yml@added-github-action-for-release