name: "Release"
on: [push]

jobs:
  build-windows:
    uses: ./.github/workflows/windows.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4