name: "Release"
on: 
  release:
    types: [published]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: NickNaso/libgs/.github/workflows/windows.yml@main    
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./builds/  

      - name: Build
        run: ls -la    

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            builds/*