name: "Release"
on: 
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "gs-*-*.tar.gz"