name: "Release"
on: [push]

jobs:
  build-windows:
    uses: ./.github/workflows/windows.yml
  build-macos:
    uses: ./.github/workflows/macos.yml

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]
    steps:
      - uses: ./.github/workflows/windows.yml