name: "Release"
on: [push]

jobs:
  build-windows:
    uses: ./builds/windows.yml@added-github-action-for-release
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4