name: "Release"
on: [workflow_call,push, pull_request]

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: win
        uses: ./.github/workflows/windows.yml

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./builds/

      - name: Start tests 
        run: npm test

