name: "Release"
on: [workflow_call,push]

jobs:
  build-windows:
    uses: ./.github/workflows/windows.yml
  build-macos:
    uses: ./.github/workflows/macos.yml
  build-linux:
    uses: ./.github/workflows/linux.yml
  build-linux-musl:
    uses: ./.github/workflows/linux-musl.yml

  test:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux, build-linux-musl]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start tests 
        run: npm test

