name: 'Build for Windows'
on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ilammy/msvc-dev-cmd@v1

            - name: Fetch source code  
              shell: bash
              run: |
                curl https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10031/ghostpdl-10.03.1.tar.gz -O -L
                tar -xzf ghostpdl-10.03.1.tar.gz
                mv ghostpdl-10.03.1 ghostpdl
            
            - name: Build
              shell: bash
              run: |
                cd ghostpdl
                nmake -f psi/msvc.mak WIN64= nsis
    