name: 'Build for Windows'
on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                architecture: [x64,x86]
        steps:
            - uses: actions/checkout@v4
            - uses: ilammy/msvc-dev-cmd@v1

            - name: Fetch source code  
              shell: bash
              run: |
                curl https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10031/ghostpdl-10.03.1.tar.gz -O -L
                tar -xzf ghostpdl-10.03.1.tar.gz
                mv ghostpdl-10.03.1 ghostpdl
            
            - name: Build
              run: |
                cd ghostpdl
                nmake -f psi\msvc32.mak WIN64= DEVSTUDIO= clean 
                nmake -f psi\msvc32.mak WIN64= SBR=1 DEVSTUDIO= 
                nmake -f psi\msvc32.mak WIN64= DEVSTUDIO= bsc
            
            - name: Creating Zip
              shell: bash
              run: |
                tar cf gs-${{ matrix.architecture }}.gz ghostpdl/bin/  
            
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                name: ghostpdl
                path: ./ghostpdl/bin/gs-${{ matrix.architecture }}.gz